### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by josherrickson** [CSCAR/workshop-r-intro#1]
Just a few suggestions as I skim through the updated documents

- Make it clearer that if they're using RStudio, they also need to have R installed.
- `7 %% 2` does work, demo it?
- Discuss not using `T` and `F` in place of `TRUE` and `FALSE` since `T` and `F` aren't protected.
- Floating point - teach `all.equal`?
- `**` is deprecated. See https://stat.ethz.ch/R-manual/R-devel/library/base/html/Arithmetic.html, under "Note".
- Introduce scripts earlier? I'd suggest it be shortly after the first time they enter a command.
     -  Also introduce comments at the same point?
- Functions - use `return`.
- Do you want to mention named vectors?
- I don't know how useful `array` is. Most people aren't dealing with >2 dimensional data.
- `$` seems under-emphasized despite its more common use that `["x"]` or `[1]`.
- Want to hide your uniqname in `getwd`?
- You prefer `haven` or `heaven`?
- No link for "messy" flower data.

**Comment by abner-hb** [comment]
Thank you! I added your suggestions months ago, but forgot to close this issue.
